from django.urls import path
from . import views
urlpatterns = [
    path('register/', views.register,name='register'),
    path('',views.home,name='home'),
    path('admin/',views.admin,name='adminpage'),
    path('login/', views.login, name='login'),
    path('patient_dashboard/<int:user_id>/', views.patient_dashboard, name='patient_dashboard'),
    path('doctor_dashboard/<int:user_id>/',views.doctor_dashboard,name='doctor_dashboard'),
    path('receptionist_dashboard/<int:user_id>/',views.receptionist_dashboard,name='receptionist_dashboard'),
    path('aboutus/',views.aboutus,name='aboutus'),
    path('alldoctor/<int:user_id>/',views.alldoctor,name='alldoctor'),
    path('book-appointment/<int:user_id>/<int:doctor_id>/', views.book_appointment, name='book_appointment'),
    path('all-bookings/<int:user_id>/',views.all_bookings,name='all_bookings'),
    path('patient-prescriptions/<int:app_id>/<int:user_id>/',views.patient_prescriptions,name="patient_prescriptions"),
    path('add-patient/<int:user_id>/',views.add_patient,name='add_patient'),
    path('show_appointments/<int:user_id>/<status>/',views.show_appointments,name='show_appointments'),
    path('update_appointment_status/<int:user_id>/<int:app_id>/',views.update_appointment_status,name='update_appointment_status'),
    path('my_prescriptions/<int:user_id>/',views.my_prescriptions,name='my_prescriptions'),
    path('pres_page/<int:p_id>/',views.pres_page,name='pres_page'),
    path('pdf_prescription_create/<int:p_id>/',views.pdf_prescription_create,name='pdf_prescription_create'),
    path('update_payment_table/<int:app_id>/',views.update_payment_table,name='update_payment_table'),
    path('final_bill/<int:p_id>/<int:user_id>/',views.final_bill,name='final_bill'),
    path('final_bill_page/<int:p_id>/',views.final_bill_page,name='final_bill_page'),
    path('pdf_final_bill/<int:p_id>/',views.pdf_final_bill,name='pdf_final_bill'),
    path('logout/', views.logout, name='logout'),
    path('rate_app/<int:user_id>/', views.rate_app, name='rate_app'),
    path('update_rating/<int:app_id>/', views.update_rating, name='update_rating'),
    path('add_doctor/<int:user_id>/',views.add_doctor,name="add_doctor"),
    path('add_receptionist/<int:user_id>/',views.add_receptionist,name="add_receptionist"),
    path('settings/<int:user_id>/',views.settings,name='settings'),
]